### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by fzn0x** [fzn0x/nuxt-web3#9]
related #6 to DEBUG error

**Comment by bl0cknumber** [comment]
```
declare module '#app' {
  interface NuxtApp extends PluginInjection { }
}
```

**Comment by fzn0x** [comment]
Starting the development at v3 branch https://github.com/fzn0x/nuxt-web3/tree/v3

**Comment by wobsoriano** [comment]
Hi, published a test module for Nuxt 3. If you're interested, I can send a PR with the exact contents of this

https://github.com/wobsoriano/nuxt-web3.js

**Comment by fzn0x** [comment]
> 

Really cool! why not? 😃

**Comment by fzn0x** [comment]
Moved to #23
